# To get started with Dependabot version updates, please read the documentation:
# https://docs.github.com/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for Node/npm dependencies in docusaurus docs
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
